### ISSUE TITLE
Anyone can delete anyone's todos

### ISSUE THREAD

**Issue by lulato** [meteor/simple-todos#23] opened 2015-06-04 02:51 UTC
Even though I added the last piece of code to pervent this I'm still struggling with this. Anyone else with this issue?

**Comment by metaprinter** [comment] 2015-06-16 13:17
@lulato is this a reference to step 9? I have an issue when I'm done with all of tutorial step 9 and try to log in as a diferent user in another incognito browser window, i see everything and am logged in as user1, also when I switch to user2 both windows go to user two.

**Comment by lulato** [comment] 2015-06-18 01:25
@metaprinter Yeah basically when I finished with the tutorial, you would think the permissions are separate. But I feel like anyone can do or see anything of each other lists.

**Comment by metaprinter** [comment] 2015-06-18 01:52
try this one, i redid steps 9-11
rivan.meteor.com

------
Robert Ivan

**Comment by lulato** [comment] 2015-06-18 02:07
I deleted your tasks :imp:

**Comment by metaprinter** [comment] 2015-06-18 11:54
i see you deleted my public todos but my private ones are still showing when i log in. 

------
Robert Ivan

**Comment by amykangweb** [comment] 2015-06-20 13:46
I'm having the same problem. Anyone can delete or update anyone's todo items. I "fixed" it for now by hiding the delete button from different users. {{#if isOwner}}

**Comment by amykangweb** [comment] 2015-06-20 15:11
I just put in a pull request to fix this issue and the throwing exceptions for correct users.

https://github.com/meteor/simple-todos/pull/26

**Comment by stubailo** [comment] 2015-07-15 01:48
Duplicate of #4

**Closed by stubailo** 2015-07-15 01:48 UTC
